// UI translations for the loading screen chrome (buttons, tabs, status text).
// Server-authored content (name, tagline, staff, announcements, changelog)
// is never translated automatically — only these fixed interface strings.
const Translations = {
    en: {
        loadingDefault: "Loading...",
        loadingSystems: "Loading Systems...",
        loadingFiles: "Loading Files...",
        infoCenterBtn: "Info Center",
        infoCenterEyebrow: "Server Information",
        infoCenterTitle: "Info Center",
        tabStaff: "Staff",
        tabUpdates: "Updates",
        socialStore: "Store",
        musicHint: "Music",
        serverLogoAlt: "Server Logo",
    },
    tr: {
        loadingDefault: "Yükleniyor...",
        loadingSystems: "Sistemler Yükleniyor...",
        loadingFiles: "Dosyalar Yükleniyor...",
        infoCenterBtn: "Bilgi Merkezi",
        infoCenterEyebrow: "Sunucu Bilgileri",
        infoCenterTitle: "Bilgi Merkezi",
        tabStaff: "Personel",
        tabUpdates: "Güncellemeler",
        socialStore: "Mağaza",
        musicHint: "Müzik",
        serverLogoAlt: "Sunucu Logosu",
    },
    es: {
        loadingDefault: "Cargando...",
        loadingSystems: "Cargando Sistemas...",
        loadingFiles: "Cargando Archivos...",
        infoCenterBtn: "Centro de Información",
        infoCenterEyebrow: "Información del Servidor",
        infoCenterTitle: "Centro de Información",
        tabStaff: "Personal",
        tabUpdates: "Actualizaciones",
        socialStore: "Tienda",
        musicHint: "Música",
        serverLogoAlt: "Logo del Servidor",
    },
    pt: {
        loadingDefault: "Carregando...",
        loadingSystems: "Carregando Sistemas...",
        loadingFiles: "Carregando Arquivos...",
        infoCenterBtn: "Central de Informações",
        infoCenterEyebrow: "Informações do Servidor",
        infoCenterTitle: "Central de Informações",
        tabStaff: "Equipe",
        tabUpdates: "Atualizações",
        socialStore: "Loja",
        musicHint: "Música",
        serverLogoAlt: "Logo do Servidor",
    },
    fr: {
        loadingDefault: "Chargement...",
        loadingSystems: "Chargement des Systèmes...",
        loadingFiles: "Chargement des Fichiers...",
        infoCenterBtn: "Centre d'Information",
        infoCenterEyebrow: "Informations du Serveur",
        infoCenterTitle: "Centre d'Information",
        tabStaff: "Personnel",
        tabUpdates: "Mises à Jour",
        socialStore: "Boutique",
        musicHint: "Musique",
        serverLogoAlt: "Logo du Serveur",
    },
    de: {
        loadingDefault: "Wird geladen...",
        loadingSystems: "Systeme werden geladen...",
        loadingFiles: "Dateien werden geladen...",
        infoCenterBtn: "Infozentrum",
        infoCenterEyebrow: "Serverinformationen",
        infoCenterTitle: "Infozentrum",
        tabStaff: "Team",
        tabUpdates: "Updates",
        socialStore: "Shop",
        musicHint: "Musik",
        serverLogoAlt: "Server-Logo",
    },
    ru: {
        loadingDefault: "Загрузка...",
        loadingSystems: "Загрузка систем...",
        loadingFiles: "Загрузка файлов...",
        infoCenterBtn: "Инфоцентр",
        infoCenterEyebrow: "Информация о сервере",
        infoCenterTitle: "Инфоцентр",
        tabStaff: "Персонал",
        tabUpdates: "Обновления",
        socialStore: "Магазин",
        musicHint: "Музыка",
        serverLogoAlt: "Логотип сервера",
    },
    pl: {
        loadingDefault: "Ładowanie...",
        loadingSystems: "Ładowanie systemów...",
        loadingFiles: "Ładowanie plików...",
        infoCenterBtn: "Centrum Informacji",
        infoCenterEyebrow: "Informacje o Serwerze",
        infoCenterTitle: "Centrum Informacji",
        tabStaff: "Zespół",
        tabUpdates: "Aktualizacje",
        socialStore: "Sklep",
        musicHint: "Muzyka",
        serverLogoAlt: "Logo Serwera",
    },
    it: {
        loadingDefault: "Caricamento...",
        loadingSystems: "Caricamento Sistemi...",
        loadingFiles: "Caricamento File...",
        infoCenterBtn: "Centro Informazioni",
        infoCenterEyebrow: "Informazioni sul Server",
        infoCenterTitle: "Centro Informazioni",
        tabStaff: "Staff",
        tabUpdates: "Aggiornamenti",
        socialStore: "Negozio",
        musicHint: "Musica",
        serverLogoAlt: "Logo del Server",
    },
    ar: {
        loadingDefault: "جارٍ التحميل...",
        loadingSystems: "جارٍ تحميل الأنظمة...",
        loadingFiles: "جارٍ تحميل الملفات...",
        infoCenterBtn: "مركز المعلومات",
        infoCenterEyebrow: "معلومات السيرفر",
        infoCenterTitle: "مركز المعلومات",
        tabStaff: "الطاقم",
        tabUpdates: "التحديثات",
        socialStore: "المتجر",
        musicHint: "الموسيقى",
        serverLogoAlt: "شعار السيرفر",
    },
};

// Native display names shown in the language dropdown (always shown in
// their own language, regardless of the currently active UI language).
const LanguageNames = {
    en: "English",
    tr: "Türkçe",
    es: "Español",
    pt: "Português",
    fr: "Français",
    de: "Deutsch",
    ru: "Русский",
    pl: "Polski",
    it: "Italiano",
    ar: "العربية",
};
